---
AWSTemplateFormatVersion: "2010-09-09"
Description:
  "CrowdStrike Cloud - AWS EKS POV"

Parameters:
  # Prerequisites
  EnvAlias:
    Type: String
    Default: 'pov'
    Description: Append a unique value to created resources for identification
  S3BucketName:
    Type: String
    Default: ""
    Description: The S3 Bucket Name where you uploaded the templates
  PermissionsBoundary:
    Type: String
    Default: ""
    Description: Permission Boundary for IAM entities if required
  # EKS and Sensor Details
  FalconSensorType:
    Description: Choose which type of Falcon Sensor to Install.  If launching on Fargate, you must choose FalconContainer
    AllowedValues:
      - FalconContainer
      - FalconNodeSensor
    Default: FalconNodeSensor
    Type: String
  EC2orFargate:
    Description: Choose which type of compute infrastructure to launch EKS
    AllowedValues:
      - EC2
      - Fargate
    Default: EC2
    Type: String
  KubernetesVersion:
    Type: String
    AllowedValues: ["1.19", "1.20", "1.21", "1.22"]
    Default: "1.21"
    Description: Kubernetes control plane version.
  # Create New VPC
  NewVPCCIDR:
    Description: 'Set new VPC CIDR Range.  Must be at least /24'
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/24
    Default: 10.1.0.0/24
    Type: String
  # Falcon Keys
  FalconCID:
    Description: 'Customer CID for the Falcon Installation'
    Type: String
    AllowedPattern: "[a-z0-9-]+"
  CrowdStrikeCloud:
    Type: String
    AllowedValues: ['us-1','us-2','eu-1']
    Default: 'us-1'
  FalconClientID:
    Description: "Client ID for the Falcon API"
    Type: String
    Default: ''
    NoEcho: true
  FalconClientSecret:
    Description: "Client Secret for the Falcon API"
    Type: String
    Default: ''
    NoEcho: true
  DockerAPIToken:
    Description: "Docker API Token generated when registering K8S Cluster in Falcon"
    Type: String
    Default: ''
    NoEcho: true
  #Prometheus
  InstallPrometheus:
    Type: String
    AllowedValues: ['true','false']
    Default: 'false'
    Description: Install Prometheus monitoring stack on EKS Cluster
  # Optional Bastion
  CreateBastion:
    Description: 'If true, create a new Linux EC2 Instance with K8s CLient Tools installed'
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Type: String  
  KeyPairName:
    Description: If CreateBastion = true, provide an existing Key Pair name for Ec2 Instance connection
    Type: String
    Default: 'keyname'
  RemoteAccessCIDR:
    Description: If CreateBastion = true, the CIDR Range to allow SSH
    Type: String
    Default: '1.1.1.1/32'
  
  # Optional detection-container
  InstallDetectionContainer:
    Type: String
    AllowedValues: ['true','false']
    Default: 'false'
    Description: Install detection-container on EKS Cluster to produce endpoint detections.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Prerequisites"
        Parameters:
          - EnvAlias
          - S3BucketName
          - PermissionsBoundary
      -
        Label:
          default: "EKS and Sensor Details"
        Parameters:
          - EC2orFargate
          - KubernetesVersion
          - FalconSensorType
      -
        Label:
          default: "Create New VPC"
        Parameters:
          - NewVPCCIDR
      -
        Label:
          default: "Configure Falcon Keys"
        Parameters:
          - FalconCID
          - FalconCIDlower
          - CrowdStrikeCloud
          - FalconClientID
          - FalconClientSecret
          - DockerAPIToken
      -
        Label:
          default: "Optional Monitoring Stack"
        Parameters:
          - InstallPrometheus
      -
        Label:
          default: "Optional Bastion Host"
        Parameters:
          - CreateBastion
          - KeyPairName
          - RemoteAccessCIDR
      -
        Label:
          default: "Optional Detection Container"
        Parameters:
          - InstallDetectionContainer

Conditions:
  InstallPrometheus: !Equals [ !Ref InstallPrometheus, 'true' ]
  CreateBastion: !Equals [ !Ref CreateBastion, 'true' ]
  EKSonEC2: !Not [ !Equals [ !Ref EC2orFargate, 'Fargate' ] ]
  EKSonFargate: !Equals [ !Ref EC2orFargate, 'Fargate' ]
  PrometheusEc2: !And [ !Condition EKSonEC2, !Condition InstallPrometheus ]
  PrometheusFargate: !And [ !Condition EKSonFargate, !Condition InstallPrometheus ]
  BastionEC2: !And [ !Condition EKSonEC2, !Condition CreateBastion ]
  BastionFargate: !And [ !Condition EKSonFargate, !Condition CreateBastion ]
  

Resources:
  EnvironmentID:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['-', [!Ref EnvAlias, 'pov-id', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      Type: String
      Value: !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      Description: SSM Parameter to set ID for CrowdStrike POV Resources.

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${S3BucketName}.s3.amazonaws.com/iam.yaml"
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvID: !GetAtt EnvironmentID.Value
        S3Bucket: !Ref S3BucketName
        PermissionsBoundary: !Ref PermissionsBoundary

  VPCStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: !Sub "https://${S3BucketName}.s3.amazonaws.com/vpc.yaml"
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvID: !GetAtt EnvironmentID.Value
        PermissionsBoundary: !Ref PermissionsBoundary
        NewVPCCIDR: !Ref NewVPCCIDR
  
  EKSControlPlaneStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL:  !Sub 'https://${S3BucketName}.s3.amazonaws.com/eksControlPlane.yaml'
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvID: !GetAtt EnvironmentID.Value
        PermissionsBoundary: !Ref PermissionsBoundary
        EKSAccessRole: !GetAtt IAMStack.Outputs.EKSAccessRoleName
        VPCID: !GetAtt VPCStack.Outputs.VPCIDOut
        Subnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1Out
        Subnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2Out
        EKSQSExtensionRoleArn: !GetAtt IAMStack.Outputs.EKSQSExtensionRoleArn

# EKS on EC2
  EKSNodeGroupStack:
    Type: AWS::CloudFormation::Stack
    Condition: EKSonEC2
    DependsOn: EKSControlPlaneStack
    Properties:
      TemplateURL:  !Sub 'https://${S3BucketName}.s3.amazonaws.com/eksNodeGroup.yaml'
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvID: !GetAtt EnvironmentID.Value
        PermissionsBoundary: !Ref PermissionsBoundary
        Subnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1Out
        Subnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2Out
        EksClusterName: !GetAtt EKSControlPlaneStack.Outputs.UniqueClusterName
        ClusterSecurityGroupId: !GetAtt EKSControlPlaneStack.Outputs.ClusterSecurityGroupId
  
  PrometheusMonitorInstall:
    Type: AWS::CloudFormation::Stack
    Condition: PrometheusEc2
    DependsOn: EKSNodeGroupStack
    Properties:
      TemplateURL: !Sub "https://${S3BucketName}.s3.amazonaws.com/prometheus.yaml"
      Parameters:
        EKSClusterName: !GetAtt EKSControlPlaneStack.Outputs.UniqueClusterName
        PermissionsBoundary: !Ref PermissionsBoundary
  
  BastionStackNodeGroup:    
    Condition: BastionEC2
    DependsOn: EKSNodeGroupStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}.s3.amazonaws.com/bastion.yaml'
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvID: !GetAtt EnvironmentID.Value
        KeyPairName: !Ref KeyPairName
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        BastionRole: !GetAtt IAMStack.Outputs.EKSAccessRoleName
        VPCID: !GetAtt VPCStack.Outputs.VPCIDOut
        VPCCIDR: !Ref NewVPCCIDR
        S3Bucket: !Ref S3BucketName
        DMZSubnetID: !GetAtt VPCStack.Outputs.DMZSubnet1Out
        ControlPlaneSecurityGroupId: !GetAtt EKSControlPlaneStack.Outputs.ControlPlaneSecurityGroupId
        EnvironmentVariables: !Sub "DETECTION_CONTAINER=${InstallDetectionContainer}, CS_CLIENT_ID=${FalconClientID}, CS_CLIENT_SECRET=${FalconClientSecret}, CS_ENV=${CrowdStrikeCloud}, CS_CID=${FalconCID}, DOCKER_API_TOKEN=${DockerAPIToken}, CS_SENSOR_TYPE=${FalconSensorType}, K8S_CLUSTER_NAME=${EKSControlPlaneStack.Outputs.UniqueClusterName}, K8S_CA_DATA=${EKSControlPlaneStack.Outputs.CAData}, K8S_VERSION=${KubernetesVersion}, K8S_ENDPOINT=${EKSControlPlaneStack.Outputs.EKSEndpoint}"

# EKS on Fargate Only
  FargateStack:
    Type: AWS::CloudFormation::Stack
    Condition: EKSonFargate
    DependsOn: EKSControlPlaneStack
    Properties:
      TemplateURL: !Sub "https://${S3BucketName}.s3.amazonaws.com/fargate.yaml"
      Parameters:
        PermissionsBoundary: !Ref PermissionsBoundary
        EnvAlias: !Ref EnvAlias
        EnvID: !GetAtt EnvironmentID.Value
        ClusterName: !GetAtt EKSControlPlaneStack.Outputs.UniqueClusterName
        Subnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1Out
        Subnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2Out
        InstallPrometheus: !Ref InstallPrometheus

  PrometheusMonitorInstallFargate:
    Type: AWS::CloudFormation::Stack
    Condition: PrometheusFargate
    DependsOn: FargateStack
    Properties:
      TemplateURL: !Sub "https://${S3BucketName}.s3.amazonaws.com/prometheus.yaml"
      Parameters:
        EKSClusterName: !GetAtt EKSControlPlaneStack.Outputs.UniqueClusterName
        PermissionsBoundary: !Ref PermissionsBoundary

  BastionStackFargate:    
    Condition: BastionFargate
    DependsOn: FargateStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}.s3.amazonaws.com/bastion.yaml'
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvID: !GetAtt EnvironmentID.Value
        KeyPairName: !Ref KeyPairName
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        BastionRole: !GetAtt IAMStack.Outputs.EKSAccessRoleName
        VPCID: !GetAtt VPCStack.Outputs.VPCIDOut
        VPCCIDR: !Ref NewVPCCIDR
        S3Bucket: !Ref S3BucketName
        DMZSubnetID: !GetAtt VPCStack.Outputs.DMZSubnet1Out
        ControlPlaneSecurityGroupId: !GetAtt EKSControlPlaneStack.Outputs.ControlPlaneSecurityGroupId
        EnvironmentVariables: !Sub "EC2_OR_FARGATE=${EC2orFargate}, DETECTION_CONTAINER=${InstallDetectionContainer}, CS_CLIENT_ID=${FalconClientID}, CS_CLIENT_SECRET=${FalconClientSecret}, CS_ENV=${CrowdStrikeCloud}, CS_CID=${FalconCID}, DOCKER_API_TOKEN=${DockerAPIToken}, CS_SENSOR_TYPE=${FalconSensorType}, K8S_CLUSTER_NAME=${EKSControlPlaneStack.Outputs.UniqueClusterName}, K8S_CA_DATA=${EKSControlPlaneStack.Outputs.CAData}, K8S_VERSION=${KubernetesVersion}, K8S_ENDPOINT=${EKSControlPlaneStack.Outputs.EKSEndpoint}"
