AWSTemplateFormatVersion: 2010-09-09
Parameters:
  PermissionsBoundary:
    Type: String
    Default: ''
  EnvAlias:
    Type: String
    Default: ''
  EnvID:
    Type: String
    Default: ''
  ClusterName:
    Type: String
    Default: ''
  Subnet1:
    Type: String
    Default: ''
  Subnet2:
    Type: String
    Default: ''
  InstallPrometheus:
    Type: String
    Default: 'false'

Conditions:
  InstallPrometheus: !Equals [ !Ref InstallPrometheus, 'true' ]
  PermissionsBoundary: !Not [ !Equals [ !Ref PermissionsBoundary, '' ] ]

Resources:
  FargateRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${EnvAlias}-fargate-role-${EnvID}"
      PermissionsBoundary:
        Fn::If:
          - PermissionsBoundary
          - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/${PermissionsBoundary}'
          - Ref: AWS::NoValue
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:eks:${AWS::Region}:${AWS::AccountId}:fargateprofile/${ClusterName}/*'
            Principal:
              Service: eks-fargate-pods.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy'

  FargateProfile:
    Type: 'AWS::EKS::FargateProfile'
    Properties:
      FargateProfileName: !Sub "${EnvAlias}-fargate-profile-${EnvID}"
      ClusterName: !Ref ClusterName
      PodExecutionRoleArn: !GetAtt FargateRole.Arn
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      Selectors:
        - Namespace: falcon-operator
        - Namespace: falcon-kubernetes-protection
        - Namespace: falcon-system
        - Namespace: falcon-system-configure
        - Namespace: detection-container

  CoreDNSFargateProfile:
    DependsOn: FargateProfile
    Type: 'AWS::EKS::FargateProfile'
    Properties:
      FargateProfileName: !Sub "${EnvAlias}-fargate-coredns-${EnvID}"
      ClusterName: !Ref ClusterName
      PodExecutionRoleArn: !GetAtt FargateRole.Arn
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      Selectors:
        - Namespace: kube-system
          Labels:
          - Key: k8s-app
            Value: kube-dns

  PrometheusProfile:
    DependsOn: CoreDNSFargateProfile
    Type: 'AWS::EKS::FargateProfile'
    Properties:
      FargateProfileName: !Sub "${EnvAlias}-fargate-prometheus-${EnvID}"
      ClusterName: !Ref ClusterName
      PodExecutionRoleArn: !GetAtt FargateRole.Arn
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      Selectors:
        - Namespace: prometheus