AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy Prometheus Stack to existing EKS cluster"

Metadata:
  cfn-lint: { config: { ignore_checks: [W9002, W9003, W9004, W9006, E9007, E9008] } }

Parameters:
  PermissionsBoundary:
    Type: String
    Default: ''
  EKSClusterName:
    Description: "Name of the EKS cluster"
    Type: String

Conditions:
  PermissionsBoundary: !Not [ !Equals [ !Ref PermissionsBoundary, '' ] ]

Resources:
  InstallPrometheus:
    Type: AWSQS::Kubernetes::HelmPOV
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: prometheus
      Namespace: prometheus
      Repository: https://prometheus-community.github.io/helm-charts
      Chart: prometheus-community/kube-prometheus-stack
      ValueYaml: |
        prometheus-node-exporter:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: eks.amazonaws.com/compute-type
                        operator: NotIn
                        values:
                          - fargate