---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Managed Nodes (SSH access: false) [created by eksctl]'

Parameters:
  EnvAlias:
    Type: String
    Default: ''
  PermissionsBoundary:
    Type: String
    Default: ''
  Subnet1:
    Type: String
    Default: ''
  Subnet2:
    Type: String
    Default: ''
  EksClusterName:
    Type: String
    Default: ''
  ClusterSecurityGroupId:
    Type: String
    Default: ''

Mappings:
  ServicePrincipalPartitionMap:
    aws:
      EC2: ec2.amazonaws.com
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
    aws-cn:
      EC2: ec2.amazonaws.com.cn
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
    aws-us-gov:
      EC2: ec2.amazonaws.com
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com

Conditions:
  PermissionsBoundary: !Not [ !Equals [ !Ref PermissionsBoundary, '' ] ]

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            Iops: 3000
            Throughput: 125
            VolumeSize: 80
            VolumeType: gp3
        MetadataOptions:
          HttpPutResponseHopLimit: 2
          HttpTokens: optional
        SecurityGroupIds:
          - !Ref ClusterSecurityGroupId
        TagSpecifications:
        - ResourceType: instance
          Tags:
          - Key: Name
            Value: k8s-cs-pov-node
          - Key: alpha.eksctl.io/nodegroup-name
            Value: ng-fffe2ff7
          - Key: alpha.eksctl.io/nodegroup-type
            Value: managed
        - ResourceType: volume
          Tags:
          - Key: Name
            Value: k8s-cs-pov-node
          - Key: alpha.eksctl.io/nodegroup-name
            Value: ng-fffe2ff7
          - Key: alpha.eksctl.io/nodegroup-type
            Value: managed
        - ResourceType: network-interface
          Tags:
          - Key: Name
            Value: k8s-cs-pov-node
          - Key: alpha.eksctl.io/nodegroup-name
            Value: ng-fffe2ff7
          - Key: alpha.eksctl.io/nodegroup-type
            Value: managed
      LaunchTemplateName:
        Fn::Sub: "${AWS::StackName}"

  ManagedNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2_x86_64
      ClusterName: !Ref EksClusterName
      InstanceTypes:
      - m5.large
      Labels:
        alpha.eksctl.io/cluster-name: !Ref EksClusterName
        alpha.eksctl.io/nodegroup-name: ng-fffe2ff7
      LaunchTemplate:
        Id:
          Ref: LaunchTemplate
      NodeRole:
        Fn::GetAtt:
        - NodeInstanceRole
        - Arn
      ReleaseVersion: 1.21.12-20220523
      NodegroupName: ng-fffe2ff7
      ScalingConfig:
        DesiredSize: 2
        MaxSize: 2
        MinSize: 2
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      Tags:
        alpha.eksctl.io/nodegroup-name: ng-fffe2ff7
        alpha.eksctl.io/nodegroup-type: managed

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        Fn::If:
          - PermissionsBoundary
          - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/${PermissionsBoundary}'
          - Ref: AWS::NoValue
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - Fn::FindInMap:
              - ServicePrincipalPartitionMap
              - Ref: AWS::Partition
              - EC2
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy
      Path: "/"
      Tags:
      - Key: Name
        Value:
          !Sub '${EnvAlias}-Node-InstanceRole'

Outputs:
  EKSNodeSecurityGroup:
    Value: !Ref ClusterSecurityGroupId